name: CI

on: push

jobs:
  test:
    runs-on: macos-14
    
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.0.app
      - name: Test
        run: swift test
